site_name: PixCore
repo_url: https://github.com/gustjose/pixcore
repo_name: gustjose/pixcore
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/Icon-pixcore.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Modo escuro

    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Modo claro
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.suggest
    - navigation.footer

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/custom.js

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
- search
- mkdocs_github_changelog

extra:
  comandos:
    test: pytest
  social:
    - icon: simple/github
      link: https://github.com/gustjose
    - icon: simple/pypi
      link: https://pypi.org/user/gustjose/

copyright: Copyright &copy; 2025 Gustavo Carreiro